### ISSUE TITLE
Error Getting Random Stream from Cache

### ISSUE THREAD

**Issue by Glyciant** [Glyciant/PurplePlus#12]
TypeError: ids.split is not a function
     at /data/purple-plus/db.js:589:108
     at connectCallback (/data/purple-plus/node_modules/mongodb/lib/mongo_client.js:515:5)
     at /data/purple-plus/node_modules/mongodb/lib/mongo_client.js:449:13
     at _combinedTickCallback (internal/process/next_tick.js:131:7)
     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Possibly passing IDs as an array somewhere rather than a CSV string.

**Comment by Glyciant** [comment]
Doesn't seem to be fixed, unfortunately.
